version: '2'

services:
  mysql:
    image: 'mysql:8'
    restart: on-failure
    volumes:
      - './dump/mysql:/dump'
      - 'mysql-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  memcached:
    image: 'memcached:1.6.17-alpine'
    restart: on-failure

  redis:
    image: 'redis:alpine'
    restart: on-failure
    command: ["redis-server", "--save 900 1", "--save 300 10", "--save 60 10000"]
    volumes:
      - './dump/redis:/data'

  php:
    build:
      dockerfile: 'docker/php/Dockerfile'
      context: '.'
    restart: on-failure
    links:
      - mysql
      - memcached
      - redis
    volumes:
      - './www:/var/www/codex'
      - 'pma-data:/usr/share'

  nginx:
    image: 'nginx:latest'
    restart: on-failure
    ports:
      - '127.0.0.1:${APP_PORT}:8080'
    links:
      - php
    volumes:
      - './docker/nginx-codex.conf:/etc/nginx/conf.d/codex.conf'
      - './www:/var/www/codex'
      - 'pma-data:/usr/share'

volumes:
  mysql-data:
  pma-data:

