--
-- Table structure for table `News`
--

CREATE TABLE `News` (
    `id` INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` INTEGER(10) UNSIGNED NOT NULL,
    `ru_text` VARCHAR(255) NOT NULL,
    `en_text` VARCHAR(255) NOT NULL,
    `type` TINYINT UNSIGNED NOT NULL,
    `dt_display` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE INNODB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
